name: Run all tests
on: [push]

jobs:
    run-pytest:
        runs-on: python
        continue-on-error: true
        steps:
            - uses: actions/checkout@v4
            - run: pip install pytest
            - run: pytest 2020/*/*.py

