name: Run all tests
on: [push]
jobs:
  prep-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        run: |
          sudo apt install python3
          sudo pip install pytest
          sudo pip install pytest-cov
      
      - name: Get Repo
        uses: actions/checkout@v4 
      
      - name: Run Tests
        run: |
          for dir in $(find . -mindepth 2 -maxdepth 2 -type d -not -path '*/.*'); do
            if [ -f "$dir/complete" ]; then
              echo "Running tests in $dir"
              pytest --cov-report html "$dir"/*_test.py || exit 1  # Running pytest in the folder with Python files
            else
              echo "'complete' file not found in $dir, skipping..."
            fi
          done
