name: Run all tests
on: [push]

jobs:
    run-pytest:
        runs-on: ubuntu-latest
        steps:
            - name: Install all python dependencies
            run: sudo apt install python3
            run: sudo pip install pytest
        
        steps:
            - name: Test scripts
            uses: actions/checkout@v4
            run: cd 2020/day_2
            if: ${{ hasFiles(complete) != '' }}
            run: pytest *_main.py

